auth/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("signin/",views.signin)
]

gleen/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from gleen import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("setup/", include("setup.urls")),
    path("", include("core.urls")),
    path("", include("configurations.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models

from gleen.helpers import notify_issue_assignees

# Create your models here.

class User(AbstractUser):
    image = models.ImageField(default="global/user.svg")
    is_admin = models.BooleanField(default=False)
    is_developer = models.BooleanField(default=False)
    is_reporter = models.BooleanField(default=False)
    
    def __str__(self):
        return self.username
    
class Plan(models.Model):
    creator=models.ForeignKey("core.User", verbose_name="creator", on_delete=models.CASCADE,related_name="created_plans")
    
    name = models.CharField(max_length=100,null=False,unique=True)
    desc = models.TextField(null=False)
    
    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
    
class ChartObject(models.Model):
    #create/update ChartObject whenever issuse status is updated
    plan=models.ForeignKey("core.Plan", verbose_name="creator", on_delete=models.CASCADE)
    
    status= models.ForeignKey("core.Status",verbose_name="status", on_delete=models.CASCADE)
    
    created_on=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{ChartObject.objects.all().count()} {self.status}(s) on {self.created_on.strftime('%Y-%m-%d %H:%M:%S')}"
    
class Issues(models.Model):
    creator=models.ForeignKey("core.User", verbose_name="creator", on_delete=models.CASCADE,related_name="created_issue")
    plan=models.ForeignKey("core.Plan", verbose_name="plan", on_delete=models.CASCADE)
    
    assignees = models.ManyToManyField("core.User",verbose_name="assignees",related_name="assigned_to")
    
    priority = models.ForeignKey('core.Priority', on_delete=models.CASCADE,null=True)
    status = models.ForeignKey('core.Status', on_delete=models.CASCADE)
    type = models.ForeignKey('core.Types', on_delete=models.CASCADE,null=True)
    
    name = models.CharField(max_length=100,null=False,unique=True) 
    desc = models.TextField(null=False)
    
    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
    
    is_locked=models.BooleanField(default=False)
    is_pinned=models.BooleanField(default=False)
    
    pinned_for=models.ManyToManyField("core.User",verbose_name="pin",related_name="pinned_for")
    
    def save(self, *args, **kwargs):
        
        
        updater = kwargs.pop('updater', None)
        
        if not self.pk:
            super().save(*args, **kwargs)
            return
            
        
        og_issue = Issues.objects.get(pk=self.pk)
        
        
        if og_issue.status!=self.status:    
            ChartObject.objects.create(plan=self.plan,status=self.status)
            Activities.objects.create(issue=self,subject=updater,verb="changed status to",object=self.status,type="status")
            payload = {
                    "type": "issue.status",
                    "issue_id": self.id,
                    "message": f"Issue #{self.id} status has changed to {self.status}",
                }
            
            notify_issue_assignees(self,payload)
            
        if og_issue.priority!=self.priority:
            Activities.objects.create(issue=self,subject=updater,verb="changed priority to",object=self.priority,type="priority")
            payload = {
                    "type": "issue.priority",
                    "issue_id": self.id,
                    "message": f"Issue #{self.id} priority has changed to {self.priority}",
                }
                
            notify_issue_assignees(self,payload)
            
        if og_issue.type!=self.type:
            Activities.objects.create(issue=self,subject=updater,verb="changed type to",object=self.type,type="type")
            payload = {
                    "type": "issue.type",
                    "issue_id": self.id,
                    "message": f"Issue #{self.id} type has changed to {self.type}",
                }
                
            notify_issue_assignees(self,payload)
        
        if og_issue.is_pinned!=self.is_pinned:
            if self.is_pinned:
                Activities.objects.create(issue=self,subject=updater,verb="pinned",object=self.name,type="pinned")
                payload = {
                    "type": "issue.pinned",
                    "issue_id": self.id,
                    "message": f"Issue #{self.id} is pinned",
                }
                
                notify_issue_assignees(self,payload)
            else:
                Activities.objects.create(issue=self,subject=updater,verb="unpinned",object=self.name,type="pinned")
                payload = {
                    "type": "issue.unpinned",
                    "issue_id": self.id,
                    "message": f"Issue #{self.id} is unpinned",
                }
                
                notify_issue_assignees(self,payload)
            
        if og_issue.is_locked!=self.is_locked:
            
            if self.is_locked:
                Activities.objects.create(issue=self,subject=updater,verb="locked",object=self.name,type="locked")
                payload = {
                    "type": "issue.locked",
                    "issue_id": self.id,
                    "message": f"Issue #{self.id} is locked",
                }
                
                
                notify_issue_assignees(self,payload)
            else:
                Activities.objects.create(issue=self,subject=updater,verb="unlocked",object=self.name,type="locked")
                payload = {
                    "type": "issue.unlocked",
                    "issue_id": self.id,
                    "message": f"Issue #{self.id} is unlocked",
                }
                
                notify_issue_assignees(self,payload)
        
        if og_issue.name!=self.name:
            Activities.objects.create(issue=self,subject=updater,verb=f"changed issue name to",object=self.name,type="name",previous_name=og_issue.name)
            payload = {
                    "type": "issue.name",
                    "issue_id": self.id,
                    "message": f"Issue #{self.id} name has changed to {self.name}",
                }
                
            notify_issue_assignees(self,payload)
        
        if og_issue.desc!=self.desc:
            Activities.objects.create(issue=self,subject=updater,verb=f"changed issue description to",object=self.desc,type="description",previous_desc=og_issue.desc)
            payload = {
                    "type": "issue.desc",
                    "issue_id": self.id,
                    "message": f"Issue #{self.id} description has changed",
                }
                
            notify_issue_assignees(self,payload)
        
        super().save(*args, **kwargs)
                    
    def __str__(self):
        return self.name


class Priority(models.Model):
    creator=models.ForeignKey("core.User", verbose_name="creator", on_delete=models.CASCADE,related_name="created_priority")
    plan=models.ManyToManyField("core.Plan", verbose_name="plan")
    
    name = models.CharField(max_length=100,null=False,unique=True)
    color = models.CharField(max_length=10,null=False) 
    desc = models.TextField(null=False)

    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

class Status(models.Model):
    creator=models.ForeignKey("core.User", verbose_name="creator", on_delete=models.CASCADE,related_name="created_status")
    plan=models.ManyToManyField("core.Plan", verbose_name="plan")
    
    name = models.CharField(max_length=100,null=False,unique=True)
    color = models.CharField(max_length=10,null=False) 
    desc = models.TextField(null=False)

    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name

    
class Types(models.Model):
    creator=models.ForeignKey("core.User", verbose_name="creator", on_delete=models.CASCADE,related_name="created_type")
    plan=models.ManyToManyField("core.Plan", verbose_name="plan")
    
    name = models.CharField(max_length=100,null=False,unique=True)
    color = models.CharField(max_length=10,null=False) 
    desc = models.TextField(null=False)

    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name


class Activities(models.Model):
    issue=models.ForeignKey("core.Issues", verbose_name="issue", on_delete=models.CASCADE)
    
    subject=models.ForeignKey("core.User", verbose_name="creator", on_delete=models.CASCADE)
    verb=models.CharField(max_length=50)
    object=models.CharField(max_length=50)
    
    MODIFICATION_TYPE=[
        ("assigned","Assigned"),
        ("unassigned","Unassigned"),
        ("status","Status"),
        ("priority","Priority"),
        ("type","Type"),
        ("pinned","Pinned"),
        ("locked","Locked"),
        ("name","Name"),
        ("description","Description")
    ]
    
    type=models.CharField(max_length=20,null=False,choices=MODIFICATION_TYPE)
    previous_name=models.CharField(max_length=100,null=True,blank=True)
    previous_desc=models.TextField(null=True,blank=True)
    
    created_on=models.DateTimeField(auto_now_add=True)
    
    @property
    def model_name(self):
        return self._meta.model_name
    
    def __str__(self):
        return f"{self.subject} {self.verb} {self.object} on {self.created_on}"

class Comment(models.Model):
    creator=models.ForeignKey("core.User", verbose_name="creator", on_delete=models.CASCADE,related_name="created_comment")
    issue=models.ForeignKey("core.Issues", verbose_name="issue", on_delete=models.CASCADE)
    

templates/component/base_popup.html
<dialog class="modal bg-drop/80" open>
    <div class="modal-box w-fit max-w-[90vw] max-h-[90vh] bg-base-200 shadow-lg shadow-drop border p-0 border-neutral">
        {% block dialog %}
        {% endblock %}
    </div>
</dialog>

templates/component/chart.html
{% load static %}
{{ chartdate|json_script:"labels-data" }}
{{ chartdata|json_script:"dataset-data" }}

<style>


</style>


<div class="flex items-center justify-center overflow-x-auto w-full">
    <div class="flex items-center justify-center overflow-x-auto" id="chart-container">
        <canvas id="chart" width="1280" style="position: relative; width: 1280px;" ></canvas>
    </div>
</div>

<script src="{% static 'js/graph.js' %}" defer></script>

templates/component/confirm_deletion.html
{% extends "component/base_popup.html" %}

{% load static %}
{% block dialog %}

<div class="flex justify-between items-center border-b border-neutral p-2 pl-4 w-full">
    <div class="flex gap-2">
        <img src="{% static 'img/alert-triangle.svg' %}" class="group-hover:brightness-50" alt="close modal?" height="24px" width="24px">
        <p class="text-lg capitalize">Confirm {{type}} Deletion !</p>
    </div>
        
    <form method="dialog">
        <button type="submit" class="bg-base-200 group m-1 p-1 rounded-full hover:brightness-200 cursor-pointer">
            <img src="{% static 'img/cross.svg' %}" class="group-hover:brightness-50" alt="close modal?" height="20px" width="20px">
        </button>
    </form>
</div>

<div class="p-4 space-y-4">
    <div class="space-y-2">
        <p>Are you sure you want to delete {{type}} <span class="font-extrabold">"{{object}}"</span>?</p>
        <p class="text-neutral">Details: {{object.desc}}</p>
    </div>
    <div class="flex gap-4">
        <form method="dialog" class="w-full">
            <button type="submit" class="w-full cursor-pointer bg-base-100 hover:bg-base-200 border border-neutral active:translate-y-[1px] p-2 rounded-box drop-shadow-md">
                Cancel
            </button>
        </form>

        <form hx-post="{{deletion_url}}" hx-swap="none" hx-on::after-request="window.location.reload()"  class="w-full">
            {% csrf_token %}
            <button type="submit" class="w-full cursor-pointer bg-white text-black hover:bg-red-500 active:translate-y-[1px] p-2 rounded-box drop-shadow-md capitalize">
                Delete {{type}}
            </button>
        </form>
        
    </div>
</div>

{% endblock dialog %}

templates/component/create_status.html
{% extends "component/base_popup.html" %}

{% load static %}
{% block dialog %}

<div class="flex justify-between items-center border-b border-neutral p-2 pl-4 min-w-96 lg:min-w-[30rem]">
    <p>Create Status</p>
    <form method="dialog">
        <button type="submit" class="bg-base-200 group m-1 p-1 rounded-full hover:brightness-200 cursor-pointer">
            <img src="{% static 'img/cross.svg' %}" class="group-hover:brightness-50" alt="" height="20px" width="20px">
        </button>
    </form>
</div>

<form class="flex flex-col p-4 gap-4" hx-post="/create_status/" hx-swap="innerHTML" hx-target="#error-status-creation">
    {% csrf_token %}
    <div class="flex items-center gap-2">
        <label class="relative flex hover rounded-box p-2 cursor-pointer hover:bg-base-100 border border-neutral">
            <div class="rounded-full border-2 w-6 h-6 justify-center items-center create-status-color-display color-preview" style="background-color: #ff000077; border-color: #f00;">&#8204;</div>
            <input type="color" required name="color" value="#ff0000" oninput="updateColor(this.value)"  class="create-status-color absolute left-0 w-1 top-full h-1 invisible opacity-0"/>
        </label>
        <input type="text" name="name" required  class="input grow" placeholder="Status Name"/>
    </div>
    <textarea name="desc" id="" class="w-full h-48 textarea border-neutral text-base align-text-top p-2 px-3 min-h-6 resize-none outline-none min-w-full" required placeholder="Write Status Description Here..."></textarea>

    <div class="grid gap-2">
        <p>Select Plans</p>
        <div class="grid gap-1 bg-base-100 p-1 rounded-box border border-neutral max-h-48 overflow-y-auto">
            {% for plan in plans %}
            <label class="flex gap-3 p-2 px-4 rounded-box cursor-pointer hover:bg-base-200">
                <input type="checkbox" checked name="plans" value="{{plan.id}}">    
                <div class="">
                    <p>{{plan}}</p>
                    <p class="text-sm text-neutral">{{plan.desc}}</p>
                </div>
            </label>
            {% endfor %}
        </div>
    </div>
    <button type="submit" class="btn bg-success border border-success-content" >Create Status</button>
    <div class="bg-red-500 shadow rounded-box" id="error-status-creation"></div>
</form>

<script>
    function updateColor(value) {
        const preview = document.querySelectorAll('.color-preview');
        preview[preview.length-1].style.backgroundColor = value + '77';
        preview[preview.length-1].style.borderColor = value;
    }
</script>
{% endblock dialog %}

templates/component/create_super_admin.html
<form method="post" action="create/" class="card bg-base-200 p-6 grid items-center justify-self-center justify-center space-y-3 w-96" enctype="multipart/form-data">
    {% csrf_token %}

    <input type="hidden" name="orgName" value="{{ name }}">
    <input type="hidden" name="orgGoal" value="{{ goal }}">
    <input type="hidden" name="orgPath" value="{{ path }}">

    <p>Let’s create your first user with full control.</p>
    <div class="grid justify-center">
        {% include "../component/image_btn.html" with imagePreviewId="csu_img_preview" imageInputId="csu_img_input" %}
    </div>
    <input name="username" type="text" placeholder="Enter name" class="input text-center" />
    <input name="password" type="password" placeholder="Enter password" class="input text-center" />
    <button class="btn outline-accent border-accent accent p-2" type="submit">Create Admin</button>
</form>

<div hx-swap-oob="true" class="hidden" id="remove_on_csu"></div>

templates/component/modify_plan.html
{% extends "component/base_popup.html" %}

{% load static %}
{% block dialog %}

<div class="flex justify-between items-center border-b border-neutral p-2 pl-4 min-w-96">
    <p>Modify plan <span class="font-extrabold">#{{plan.id}}</span></p>
    <form method="dialog">
        <button type="submit" class="bg-base-200 group m-1 p-1 rounded-full hover:brightness-200 cursor-pointer">
            <img src="{% static 'img/cross.svg' %}" class="group-hover:brightness-50" alt="" height="20px" width="20px">
        </button>
    </form>
</div>

<form action="/plan_modification/{{plan.id}}/" method="post" class="flex flex-col gap-4 p-4 min-w-96">
    {% csrf_token %}
    <label for="plan-name-create-modal" class="space-y-1.5"> 
        <p>Title of plan</p>
        <input class="w-full input border-neutral bg-base-400 text-base p-3 outline-none" name="plan_name" required value="{{plan.name}}" id="plan-name-create-modal" type="text" placeholder="Plan name..."/>
    </label>
    <label for="plan-desc-create-modal" class="space-y-1.5"> 
        <p>Description of plan</p>
        <textarea class="w-full h-48 textarea border-neutral text-base align-text-top p-2 px-3 min-h-6 resize-none outline-none min-w-full" name="plan_desc" required id="plan-desc-create-modal" type="text" placeholder="Write Description here...">{{plan.desc}}</textarea>
    </label>
    <button type="submit" class="text-lg btn bg-success border-success-content font-medium">Change Plan Details</button>
</form>
{% endblock dialog %}

templates/component/modify_priority.html
{% extends "component/base_popup.html" %}

{% load static %}
{% block dialog %}

<div class="flex justify-between items-center border-b border-neutral p-2 pl-4 min-w-96 lg:min-w-[30rem]">
    Modify Priority <span class="font-extrabold">{{priority.name}}</span>
    <form method="dialog">
        <button type="submit" class="bg-base-200 group m-1 p-1 rounded-full hover:brightness-200 cursor-pointer">
            <img src="{% static 'img/cross.svg' %}" class="group-hover:brightness-50" alt="" height="20px" width="20px">
        </button>
    </form>
</div>

<form class="flex flex-col p-4 gap-4" hx-post="/priority_modification/{{priority.id}}/" hx-swap="innerHTML" hx-target="#error-priority-creation">
    {% csrf_token %}
    <div class="flex items-center gap-2">
        <label class="relative flex hover rounded-box p-2 cursor-pointer hover:bg-base-100 border border-neutral">
            <div class="rounded-full w-4 h-4 justify-center items-center create-priority-color-display color-preview-priority-modify" style="background-color: {{priority.color}};">&#8204;</div>
            <input type="color" required name="color" value="{{priority.color}}" oninput="updateColor(this.value)"  class="create-priority-color absolute left-0 w-1 top-full h-1 invisible opacity-0"/>
        </label>
        <input type="text" name="name" required value="{{priority.name}}"  class="input grow" placeholder="Priority Name"/>
    </div>
    <textarea name="desc" class="w-full h-48 textarea border-neutral text-base align-text-top p-2 px-3 min-h-6 resize-none outline-none min-w-full" required placeholder="Write Priority Description Here...">{{priority.desc}}</textarea>

    <div class="grid gap-2">
        <p>Select Plans</p>
        <div class="grid gap-1 bg-base-100 p-1 rounded-box border border-neutral max-h-48 overflow-y-auto">
            {% for plan in plans %}
                <label class="flex gap-3 p-2 px-4 rounded-box cursor-pointer hover:bg-base-200">
                    <input type="checkbox"
                        name="plans"
                        value="{{ plan.id }}"
                        {% if plan.id in selected_plan_ids %}checked{% endif %}>
                    <div>
                        <p>{{ plan }}</p>
                        <p class="text-sm text-neutral">{{ plan.desc }}</p>
                    </div>
                </label>
            {% endfor %}
        </div>
    </div>
    <button type="submit" class="btn bg-success border border-success-content" >Create Priority</button>
    <div class="bg-red-500 shadow rounded-box" id="error-priority-creation"></div>
</form>

<script>
    function updateColor(value) {
        const preview = document.querySelectorAll('.color-preview-priority-modify');
        preview[preview.length-1].style.backgroundColor = value;
    }
</script>
{% endblock dialog %}

templates/component/modify_status.html
{% extends "component/base_popup.html" %}

{% load static %}
{% block dialog %}

<div class="flex justify-between items-center border-b border-neutral p-2 pl-4 min-w-96 lg:min-w-[30rem]">
    Modify user <span class="font-extrabold">{{status.name}}</span>
    <form method="dialog">
        <button type="submit" class="bg-base-200 group m-1 p-1 rounded-full hover:brightness-200 cursor-pointer">
            <img src="{% static 'img/cross.svg' %}" class="group-hover:brightness-50" alt="" height="20px" width="20px">
        </button>
    </form>
</div>

<form class="flex flex-col p-4 gap-4" hx-post="/status_modification/{{status.id}}/" hx-swap="innerHTML" hx-target="#error-status-creation">
    {% csrf_token %}
    <div class="flex items-center gap-2">
        <label class="relative flex hover rounded-box p-2 cursor-pointer hover:bg-base-100 border border-neutral">
            <div class="rounded-full border-2 w-6 h-6 justify-center items-center create-status-color-display color-preview-modify" style="background-color: {{status.color}}77; border-color: {{status.color}};">&#8204;</div>
            <input type="color" required name="color" value="{{status.color}}" oninput="updateColor(this.value)"  class="create-status-color absolute left-0 w-1 top-full h-1 invisible opacity-0"/>
        </label>
        <input type="text" name="name" required value="{{status.name}}"  class="input grow" placeholder="Status Name"/>
    </div>
    <textarea name="desc" class="w-full h-48 textarea border-neutral text-base align-text-top p-2 px-3 min-h-6 resize-none outline-none min-w-full" required placeholder="Write Status Description Here...">{{status.desc}}</textarea>

    <div class="grid gap-2">
        <p>Select Plans</p>
        <div class="grid gap-1 bg-base-100 p-1 rounded-box border border-neutral max-h-48 overflow-y-auto">
            {% for plan in plans %}
                <label class="flex gap-3 p-2 px-4 rounded-box cursor-pointer hover:bg-base-200">
                    <input type="checkbox"
                        name="plans"
                        value="{{ plan.id }}"
                        {% if plan in status.plan.all %}checked{% endif %}>
                    <div>
                        <p>{{ plan }}</p>
                        <p class="text-sm text-neutral">{{ plan.desc }}</p>
                    </div>
                </label>
            {% endfor %}
        </div>
    </div>
    <button type="submit" class="btn bg-success border border-success-content" >Create Status</button>
    <div class="bg-red-500 shadow rounded-box" id="error-status-creation"></div>
</form>

<script>
    function updateColor(value) {
        const preview = document.querySelectorAll('.color-preview-modify');
        preview[preview.length-1].style.backgroundColor = value + '77';
        preview[preview.length-1].style.borderColor = value;
    }
</script>
{% endblock dialog %}

templates/component/modify_user.html
{% extends "component/base_popup.html" %}

{% load static %}
{% block dialog %}

<div class="flex justify-between items-center border-b border-neutral p-2 pl-4 min-w-96 lg:min-w-[30rem]">
    <p>Modify user <span class="font-extrabold">{{user.username}}</span></p>
    <form method="dialog">
        <button type="submit" class="bg-base-200 group m-1 p-1 rounded-full hover:brightness-200 cursor-pointer">
            <img src="{% static 'img/cross.svg' %}" class="group-hover:brightness-50" alt="" height="20px" width="20px">
        </button>
    </form>
</div>

<form class="grid grid-cols-1 lg:grid-cols-2 p-4 w-full peer-checked:hidden"  autocomplete="off" enctype="multipart/form-data" hx-post="/user_modification/{{user.id}}/" hx-swap="none" hx-target="">
    {% csrf_token %}
    <div class="flex w-full items-center justify-center">
        
        {% include "component/image_btn.html" with size="h-16 w-16" extraStyle="p-8" previewImage=user.image.url imagePreviewId=preview_id imageInputId=input_id %}
    
    </div>
    <div class="flex flex-col gap-2">
        <div class="flex flex-col gap-1">
            <p>Name</p> 
            <label class="input grow w-full">
                &#8204;
                <input name="username" type="text" placeholder="&#8204;User&#8204; Name&#8204;" value="{{user.username}}"/>
            </label>
        </div>
        <div class="flex flex-col gap-1">
            <p>Email</p> 
            <label class="input grow w-full">
                &#8204;
                <input name="email" type="email"  placeholder="&#8204;Email&#8204;@examplecom&#8204;" value="{{user.email}}"/>
            </label>
        </div>
        <div class="flex flex-col gap-1">
            <p>Password</p> 
            <label class="input grow w-full">
                &#8204;
                <input name="password" type="password" placeholder="&#8204;User's&#8204; pass&#8204;word&#8204;" value="        "/>
            </label>
        </div>
        <p>Role</p> 
        <div class="flex gap-2 items-center">
            <div class="">
                <input type="radio" class="peer hidden" id="role-admin" required value="1" {% if user.is_admin %}checked{% endif %} name="role"/>
                <label for="role-admin" class="peer-checked:text-black peer-checked:bg-white cursor-pointer rounded-box border border-neutral bg-base-200 p-2">
                    Admin
                </label>
            </div>
            <div class="">
                <input type="radio" class="peer hidden" id="role-dev" value="2" required name="role" {% if user.is_developer %}checked{% endif %}/>
                <label for="role-dev" class="peer-checked:text-black peer-checked:bg-white cursor-pointer rounded-box border border-neutral bg-base-200 p-2">
                    Developer
                </label>
            </div>
            <div class="">
                <input type="radio" class="peer hidden" id="role-review" {% if user.is_reporter %}checked{% endif %} required value="3" name="role"/>
                <label for="role-review" class="peer-checked:text-black peer-checked:bg-white cursor-pointer rounded-box border border-neutral bg-base-200 p-2">
                    Reviewer
                </label>
            </div>
        </div>
        <button type="submit"  class="mt-2 btn bg-success border border-success-content">Modify User Details</button>
        <div class="bg-red-700 rounded-box" id="error-user"></div>
    </div>
</form>
{% endblock dialog %}

templates/component/plan_table.html
{% load static %}
{% for plan in plans %}
    <div class="flex items-center justify-between border-t border-neutral p-4 relative">
        <div class="">
            <p>{{plan.name}}</p>
            <p class="text-sm text-neutral">{{plan.desc}}</p>
        </div>
        <div class="flex gap-2 items-center">
            <p class="text-sm">{{plan.issues_set.count}} issues</p>
            <label class="cursor-pointer hover:bg-base-100 p-2  rounded-full shadow-none relative"  type="button" aria-label="plan options">
                <svg width="16" height="16" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M7.20039 12.5001C7.20039 13.8256 6.12587 14.9001 4.80039 14.9001C3.47491 14.9001 2.40039 13.8256 2.40039 12.5001C2.40039 11.1746 3.47491 10.1001 4.80039 10.1001C6.12587 10.1001 7.20039 11.1746 7.20039 12.5001Z" stroke="white" stroke-width="2"/>
                    <path d="M14.4004 12.5001C14.4004 13.8256 13.3259 14.9001 12.0004 14.9001C10.6749 14.9001 9.60039 13.8256 9.60039 12.5001C9.60039 11.1746 10.6749 10.1001 12.0004 10.1001C13.3259 10.1001 14.4004 11.1746 14.4004 12.5001Z" stroke="white" stroke-width="2"/>
                    <path d="M21.6004 12.5001C21.6004 13.8256 20.5259 14.9001 19.2004 14.9001C17.8749 14.9001 16.8004 13.8256 16.8004 12.5001C16.8004 11.1746 17.8749 10.1001 19.2004 10.1001C20.5259 10.1001 21.6004 11.1746 21.6004 12.5001Z" stroke="white" stroke-width="2"/>
                </svg>
                <input class="peer absolute top-0 left-0 hidden h-6 w-6"  checked type="checkbox"/>
                <dialog class="absolute -translate-x-full top-full card bg-base-100 border border-neutral p-2 peer-checked:hidden z-50 w-44 space-y-1" open>
                    <button type="button" class="flex p-2 rounded-[10px] cursor-pointer gap-2 active:translate-y-[1px] bg-base-100 hover:bg-base-200 justify-start shadow-none"
                            hx-target="#top-layer" 
                            hx-swap="innerHTML"
                            hx-get="/plan_modification/{{plan.id}}/">
                        <img src="{% static 'img/modify.svg' %}" alt="delete button" height="18px" width="18px">
                        <p>Modify Plan</p>
                    </button>
                    <button type="button" class="flex p-2 rounded-[10px] cursor-pointer gap-2 text-red-500 active:translate-y-[1px] bg-base-100 hover:bg-base-200 justify-start shadow-none"
                            hx-target="#top-layer" 
                            hx-swap="innerHTML"
                            hx-get="/plan_deletion/{{plan.id}}/" >
                        <img src="{% static 'img/trashcan-red.svg' %}" alt="delete button" height="18px" width="18px">
                        <p>Delete Plan</p>
                    </button>
                </dialog>
            </label>
        </div>
    </div>
{% endfor %}